In [4]:
from multi_modal_edge_ai.models.anomaly_detection.data_access.parser import parse_file_with_idle
from multi_modal_edge_ai.models.anomaly_detection.ml_models.local_outlier_factor import LOF
from multi_modal_edge_ai.models.anomaly_detection.ml_models.isolation_forest import IForest
from multi_modal_edge_ai.models.anomaly_detection.ml_models.one_class_svm import OCSVM
from multi_modal_edge_ai.models.anomaly_detection.ml_models.autoencoder import Autoencoder
from multi_modal_edge_ai.models.anomaly_detection.ml_models.lstm_autoencoder import LSTMAutoencoder
from multi_modal_edge_ai.models.anomaly_detection.train_and_eval.model_validator import model_train_eval
from multi_modal_edge_ai.models.anomaly_detection.train_and_eval.hyperparameter_config import HyperparameterConfig as Hparams
import torch.nn as nn


data = parse_file_with_idle("../../public_datasets/Aruba_Idle_Squashed.csv")

In [2]:
 # Basic LOF model with changed hyperparameters
# Novelty set to True means that the model will use LocalOutlierFactor for novelty detection and data is outlier-free during training

lof = LOF()
lofParams = {
    "n_neighbors": 300,
    "algorithm": "auto",
    "leaf_size": 40,
    "metric": "minkowski",
    "p": 2,
    "contamination": "auto",
    "novelty": True
}

hp = Hparams(lof_hparams=lofParams, clean_test_data_ratio = 0.1,
             window_size= 8, window_slide= 1, one_hot=False)
(avg, cm) = model_train_eval(lof, data, hp)
print(avg)
print(cm)
(tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
print("Accuracy: ", (tp + tn) / (tp + tn + fp + fn))
print("Precision: ", tp / (tp + fp))
print("Recall: ", tp / (tp + fn))
print("F1: ", 2 * tp/(2 * tp + fp + fn))


clean_df: 8890 anomalous_df: 729
5
0.5905411163187048
[[1376   82]
 [ 879   10]]
Accuracy:  0.5905411163187048
Precision:  0.943758573388203
Recall:  0.61019955654102
F1:  0.7411796391058443


In [3]:
# Basic LOF model with changed hyperparameters and Novelty set to True and batch size of 16
# Novelty set to True means that the model will use LocalOutlierFactor for novelty detection and data is outlier-free during training

lof = LOF()
lofParams = {
    "n_neighbors": 4000,
    "algorithm": "auto",
    "leaf_size": 400,
    "metric": "minkowski",
    "p": 2,
    "contamination": 0.001,
    "novelty": True
}

hp = Hparams(lof_hparams=lofParams, clean_test_data_ratio = 0.15, window_size= 8, window_slide= 1)
(avg, cm) = model_train_eval(lof, data, hp)
print(avg)
print(cm)
(tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
print("Accuracy: ", (tp + tn) / (tp + tn + fp + fn))
print("Precision: ", tp / (tp + fp))
print("Recall: ", tp / (tp + fn))
print("F1: ", 2 * tp/(2 * tp + fp + fn))

clean_df: 8890 anomalous_df: 729
12
0.5069867431028305
[[ 111 1347]
 [  29 1304]]
Accuracy:  0.5069867431028305
Precision:  0.07613168724279835
Recall:  0.7928571428571428
F1:  0.13892365456821026


In [4]:
# Basic LOF model with changed hyperparameters and Novelty set to True and batch size of 64
# Novelty set to True means that the model will use LocalOutlierFactor for novelty detection and data is outlier-free during training

lof = LOF()
lofParams = {
    "n_neighbors": 2000,
    "algorithm": "auto",
    "leaf_size": 300,
    "metric": "minkowski",
    "p": 2,
    "contamination": "auto",
    "novelty": True
}

hp = Hparams(lof_hparams=lofParams, clean_test_data_ratio = 0.15, window_size= 8, window_slide= 1, one_hot=False)
(avg, cm) = model_train_eval(lof, data, hp)
print(avg)
print(cm)
(tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
print("Accuracy: ", (tp + tn) / (tp + tn + fp + fn))
print("Precision: ", tp / (tp + fp))
print("Recall: ", tp / (tp + fn))
print("F1: ", 2 * tp/(2 * tp + fp + fn))

clean_df: 8890 anomalous_df: 729
5
0.5206019347903977
[[ 166 1292]
 [  46 1287]]
Accuracy:  0.5206019347903977
Precision:  0.11385459533607682
Recall:  0.7830188679245284
F1:  0.19880239520958085


In [3]:
iforest = IForest()

iforestParams = {
    "n_estimators": 1000,
    "max_samples": "auto",
    "contamination": 0.1,
    "max_features": 1.0,
    "bootstrap": False,
    "n_jobs": -1,
    "random_state": 42,
    "verbose": 0,
}

hp = Hparams(i_forest_hparams=iforestParams, window_size= 8, window_slide= 1)
(avg, cm) = model_train_eval(iforest, data, hp)
print(avg)
print(cm)
(tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
print("Accuracy: ", (tp + tn) / (tp + tn + fp + fn))
print("Precision: ", tp / (tp + fp))
print("Recall: ", tp / (tp + fn))
print("F1: ", 2 * tp/(2 * tp + fp + fn))

clean_df: 8890 anomalous_df: 729
12


KeyboardInterrupt: 

In [ ]:
iforest = IForest()

iforestParams = {
    "n_estimators": 1000,
    "max_samples": "auto",
    "contamination": 0.1,
    "max_features": 1.0,
    "bootstrap": False,
    "n_jobs": -1,
    "random_state": 42,
    "verbose": 0,
}

hp = Hparams(i_forest_hparams=iforestParams, window_size= 8, window_slide= 1, one_hot=False)
(avg, cm) = model_train_eval(iforest, data, hp)
print(avg)
print(cm)
(tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
print("Accuracy: ", (tp + tn) / (tp + tn + fp + fn))
print("Precision: ", tp / (tp + fp))
print("Recall: ", tp / (tp + fn))
print("F1: ", 2 * tp/(2 * tp + fp + fn))

In [4]:
ocsvm = OCSVM()

ovscmParams = {
    "kernel": "rbf",
    "degree": 3,
    "gamma": "scale",
    "coef0": 0.0,
    "tol": 0.001,
    "nu": 0.01,
    "shrinking": True,
    "cache_size": 2400,
    "verbose": False,
    "max_iter": -1,
}

hp = Hparams(ocsvm_hparams=ovscmParams, anomaly_generation_ratio = 11, clean_test_data_ratio = 0.25,window_size= 8, window_slide= 1,one_hot=False)
(avg, cm) = model_train_eval(ocsvm, data, hp)
print(avg)
print(cm)
(tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
print("Accuracy: ", (tp + tn) / (tp + tn + fp + fn))
print("Precision: ", tp / (tp + fp))
print("Recall: ", tp / (tp + fn))
print("F1: ", 2 * tp/(2 * tp + fp + fn))


clean_df: 8890 anomalous_df: 729
5
[1 0 1 ... 1 1 0]
[1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0

In [7]:
autoenc = Autoencoder([96,64,32,16], [16,32,64,96],nn.ReLU(), nn.Sigmoid())

hp = Hparams(batch_size=16,  n_epochs=10, anomaly_generation_ratio = 11, clean_test_data_ratio=0.2, window_size= 8, window_slide= 1)
(avg, cm) = model_train_eval(autoenc, data, hp)
print(avg)
print(cm)
(tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
print("Accuracy:", (tp + tn) / (tp + tn + fp + fn))
print("Precision: ", tp / (tp + fp))
print("Recall: ", tp / (tp + fn))
print("F1: ", 2 * tp / (2 * tp + fp + fn))

clean_df: 8890 anomalous_df: 729
12
Epoch 1 training loss: 0.05389717221260071
Epoch 2 training loss: 0.030980540439486504
Epoch 3 training loss: 0.023487167432904243
Epoch 4 training loss: 0.020996732637286186
Epoch 5 training loss: 0.019222674891352654
Epoch 6 training loss: 0.017535774037241936
Epoch 7 training loss: 0.016274292021989822
Epoch 8 training loss: 0.01566317304968834
Epoch 9 training loss: 0.015262589789927006
Epoch 10 training loss: 0.014593065716326237
0.2847235417062512
[[1318 7430]
 [  99 1679]]
Accuracy: 0.2847235417062512
Precision:  0.1843231968382918
Recall:  0.9443194600674916
F1:  0.30844126021860935


In [9]:
autoenc = Autoencoder([40, 32, 16, 8], [8, 16, 32, 40], nn.ReLU(), nn.Sigmoid())

hp = Hparams(batch_size=32, n_epochs=16, clean_test_data_ratio=0.2,window_size=8, window_slide=1, one_hot=False)
(avg, cm) = model_train_eval(autoenc, data, hp)
print(avg)
print(cm)
(tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
print("Accuracy:", (tp + tn) / (tp + tn + fp + fn))
print("Precision: ", tp / (tp + fp))
print("Recall: ", tp / (tp + fn))
print("F1: ", 2 * tp / (2 * tp + fp + fn))

clean_df: 8890 anomalous_df: 729
5
[0 0 0 ... 1 0 1]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [2]:
ltsm = LSTMAutoencoder(12, 8, 8, 16, 16)

hp = Hparams(batch_size=16, n_epochs=32, clean_test_data_ratio=0.2, window_size=8, window_slide=1, one_hot=True)

(avg, cm) = model_train_eval(ltsm, data, hp)
print(avg)
print(cm)
(tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
print("Accuracy:", (tp + tn) / (tp + tn + fp + fn))
print("Precision: ", tp / (tp + fp))
print("Recall: ", tp / (tp + fn))
print("F1: ", 2 * tp / (2 * tp + fp + fn))


clean_df: 8890 anomalous_df: 729
12
Epoch 1 training loss: 0.07760713093037244
Epoch 2 training loss: 0.07725755977669586
Epoch 3 training loss: 0.0772386808702628
Epoch 4 training loss: 0.07725333552849474
Epoch 5 training loss: 0.07720437902104449
Epoch 6 training loss: 0.07721456329896627
Epoch 7 training loss: 0.0772136117869106
Epoch 8 training loss: 0.07721375107463486
Epoch 9 training loss: 0.07718426470631153
Epoch 10 training loss: 0.07720113484895001
Epoch 11 training loss: 0.07719907346490616
Epoch 12 training loss: 0.07718318898107174
Epoch 13 training loss: 0.07717363352660002
Epoch 14 training loss: 0.07718654360969973
Epoch 15 training loss: 0.07717847603837319
Epoch 16 training loss: 0.07719744948766648
Epoch 17 training loss: 0.07721296846458041
Epoch 18 training loss: 0.07720602415680164
Epoch 19 training loss: 0.07716414992486968
Epoch 20 training loss: 0.07716112782344792
Epoch 21 training loss: 0.07718445156324819
Epoch 22 training loss: 0.07716832268737986
Epoch 2

In [ ]:
# Grid search for OCSVM
ocsvm = OCSVM()

kernels = ["rbf", "linear", "poly", "sigmoid"]
degrees = [3, 4, 5]
gammas = ["scale", "auto"]
coef0s = [0.0, 0.1, 0.2, 0.3]
tols = [0.0001, 0.00001]

for k in kernels:
    for d in degrees:
        for g in gammas:
            for c in coef0s:
                for t in tols:
                    ovscmParams = {
                        "kernel": k,
                        "degree": d if k == "poly" else 3,
                        "gamma": g,
                        "coef0": c if k == "poly" or k == "sigmoid" else 0.0,
                        "tol": t,
                        "nu": 0.001,
                        "shrinking": True,
                        "cache_size": 3200,
                        "verbose": False,
                        "max_iter": -1,
                    }

                    hp = Hparams(ocsvm_hparams=ovscmParams, anomaly_generation_ratio=11,
                                 clean_test_data_ratio=0.25, window_size=8, window_slide=1,
                                 one_hot=False)
                    (avg, cm) = model_train_eval(ocsvm, data, hp)
                    print("for kernel: ", k, " degree: ", d, " gamma: ", g, " coef0: ", c, " tol: ", t)
                    print(avg)
                    print(cm)
                    (tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
                    print("Accuracy: ", (tp + tn) / (tp + tn + fp + fn))
                    print("Precision: ", tp / (tp + fp))
                    print("Recall: ", tp / (tp + fn))
                    print("F1: ", 2 * tp / (2 * tp + fp + fn))
                    print("---------------------------------------------------")

clean_df: 8890 anomalous_df: 729
5
for kernel:  rbf  degree:  3  gamma:  scale  coef0:  0.0  tol:  0.0001
0.7262534184138559
[[6972 1776]
 [1227  995]]
Accuracy:  0.7262534184138559
Precision:  0.3590761457957416
Recall:  0.44779477947794777
F1:  0.3985579811736431
---------------------------------------------------
clean_df: 8890 anomalous_df: 729
5
for kernel:  rbf  degree:  3  gamma:  scale  coef0:  0.0  tol:  1e-05
0.697538742023701
[[6620 2128]
 [1190 1032]]
Accuracy:  0.697538742023701
Precision:  0.3265822784810127
Recall:  0.46444644464446444
F1:  0.3835005574136009
---------------------------------------------------
clean_df: 8890 anomalous_df: 729
5
for kernel:  rbf  degree:  3  gamma:  scale  coef0:  0.1  tol:  0.0001
0.7302643573381951
[[6966 1782]
 [1177 1045]]
Accuracy:  0.7302643573381951
Precision:  0.36964980544747084
Recall:  0.47029702970297027
F1:  0.4139433551198257
---------------------------------------------------
clean_df: 8890 anomalous_df: 729
5
for kernel:  

In [4]:
ocsvm = OCSVM()

ovscmParams = {
    "kernel": "rbf",
    "degree": 3,
    "gamma": "scale",
    "coef0": 0.0,
    "tol": 0.0001,
    "nu": 0.001,
    "shrinking": True,
    "cache_size": 2800,
    "verbose": False,
    "max_iter": -1,
}

hp = Hparams(ocsvm_hparams=ovscmParams, anomaly_generation_ratio = 11, clean_test_data_ratio = 0.30,window_size= 8, window_slide= 1,one_hot=False)
(avg, cm) = model_train_eval(ocsvm, data, hp)
print(avg)
print(cm)
(tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
print("Accuracy: ", (tp + tn) / (tp + tn + fp + fn))
print("Precision: ", tp / (tp + fp))
print("Recall: ", tp / (tp + fn))
print("F1: ", 2 * tp/(2 * tp + fp + fn))

clean_df: 8890 anomalous_df: 729
5
0.6910205869469995
[[6581 2167]
 [1360 1307]]
Accuracy:  0.6910205869469995
Precision:  0.37622337363270003
Recall:  0.49006374203224595
F1:  0.425663572708028


In [ ]:
# Grid search OCSVM with poly

ocsvm = OCSVM()

degrees = [3, 4, 5]
gammas = ["scale", "auto"]
coef0s = [0.0, 0.1, 0.2, 0.3]
tols = [0.001, 0.0001]

for d in degrees:
    for g in gammas:
        for c in coef0s:
            for t in tols:
                ovscmParams = {
                    "kernel": "poly",
                    "degree": d,
                    "gamma": g,
                    "coef0": c,
                    "tol": t,
                    "nu": 0.001,
                    "shrinking": True,
                    "cache_size": 3200,
                    "verbose": False,
                    "max_iter": -1,
                }

                hp = Hparams(ocsvm_hparams=ovscmParams, anomaly_generation_ratio=0.01,
                             clean_test_data_ratio=0.25, window_size=8, window_slide=1,
                             one_hot=False)
                (avg, cm) = model_train_eval(ocsvm, data, hp)
                print("for degree: ", d, " gamma: ", g, " coef0: ", c, " tol: ", t)
                print(avg)
                print(cm)
                (tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
                print("Accuracy: ", (tp + tn) / (tp + tn + fp + fn))
                print("Precision: ", tp / (tp + fp))
                print("Recall: ", tp / (tp + fn))
                print("F1: ", 2 * tp / (2 * tp + fp + fn))
                print("---------------------------------------------------")


In [8]:
ocsvm = OCSVM()

ovscmParams = {
    "kernel": "poly",
    "degree": 5,
    "gamma": "scale",
    "coef0": 0.3,
    "tol": 0.001,
    "nu": 0.001,
    "shrinking": True,
    "cache_size": 2800,
    "verbose": False,
    "max_iter": -1,
}

hp = Hparams(ocsvm_hparams=ovscmParams, anomaly_generation_ratio = 0.01, clean_test_data_ratio = 0.30,window_size= 8, window_slide= 1,one_hot=False)
(avg, cm) = model_train_eval(ocsvm, data, hp)
print(avg)
print(cm)
(tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
print("Accuracy: ", (tp + tn) / (tp + tn + fp + fn))
print("Precision: ", tp / (tp + fp))
print("Recall: ", tp / (tp + fn))
print("F1: ", 2 * tp/(2 * tp + fp + fn))

clean_df: 8890 anomalous_df: 729
5
0.6518787878787878
[[  23 1435]
 [   1 2666]]
Accuracy:  0.6518787878787878
Precision:  0.6500853450377957
Recall:  0.9996250468691413
F1:  0.7878250591016549


In [ ]:
# Grid search for LOF

lof = LOF()

n_neighbors = [1500,2000,2500,3000]
leaf_sizes = [200,250,300,350]

for n in n_neighbors:
    for l in leaf_sizes:
        lofParams = {
            "n_neighbors": n,
            "algorithm": "auto",
            "leaf_size": l,
            "metric": "minkowski",
            "p": 2,
            "metric_params": None,
            "contamination": "auto",
            "novelty": True,
            "n_jobs": -1,
        }

        hp = Hparams(lof_hparams=lofParams, anomaly_generation_ratio = 0.01, clean_test_data_ratio = 0.30,window_size= 8, window_slide= 1,one_hot=False)
        (avg, cm) = model_train_eval(lof, data, hp)
        print("for n_neighbors: ", n, " leaf_size: ", l)
        print(avg)
        print(cm)
        (tp, tn, fp, fn) = (cm[1][1], cm[0][0], cm[0][1], cm[1][0])
        print("Accuracy: ", (tp + tn) / (tp + tn + fp + fn))
        print("Precision: ", tp / (tp + fp))
        print("Recall: ", tp / (tp + fn))
        print("F1: ", 2 * tp / (2 * tp + fp + fn))
        print("---------------------------------------------------")


clean_df: 8890 anomalous_df: 729
5
for n_neighbors:  1500  leaf_size:  200
0.6681212121212121
[[ 217 1241]
 [ 128 2539]]
Accuracy:  0.6681212121212121
Precision:  0.6716931216931217
Recall:  0.9520059992500938
F1:  0.7876531720179929
---------------------------------------------------
clean_df: 8890 anomalous_df: 729
5
for n_neighbors:  1500  leaf_size:  250
0.6678787878787878
[[ 213 1245]
 [ 125 2542]]
Accuracy:  0.6678787878787878
Precision:  0.6712437285450225
Recall:  0.9531308586426697
F1:  0.7877285404400372
---------------------------------------------------
clean_df: 8890 anomalous_df: 729
5
for n_neighbors:  1500  leaf_size:  300
0.6693333333333333
[[ 215 1243]
 [ 121 2546]]
Accuracy:  0.6693333333333333
Precision:  0.6719451042491422
Recall:  0.9546306711661042
F1:  0.788723667905824
---------------------------------------------------
clean_df: 8890 anomalous_df: 729
5
for n_neighbors:  1500  leaf_size:  350
0.6676363636363636
[[ 210 1248]
 [ 123 2544]]
Accuracy:  0.667636363